export type Position = "C" | "1B" | "2B" | "3B" | "SS" | "OF" | "SP" | "RP";
export type RiskLevel = "low" | "medium" | "high";
export type DepthStatus = "starter" | "backup" | "prospect";

export interface Player {
  id: string;
  name: string;
  mlbTeam: string;
  positions: Position[];
  riskLevel: RiskLevel;
  depthStatus: DepthStatus;
  estimatedValue: number;
  isEligible: boolean;
}

export const mockPlayers: Player[] = [
  {
    id: "1",
    name: "Jarren Duran",
    mlbTeam: "BOS",
    positions: ["OF"],
    riskLevel: "low",
    depthStatus: "starter",
    estimatedValue: 38,
    isEligible: true,
  },
  {
    id: "2",
    name: "Corbin Carroll",
    mlbTeam: "ARI",
    positions: ["OF"],
    riskLevel: "medium",
    depthStatus: "starter",
    estimatedValue: 32,
    isEligible: true,
  },
  {
    id: "3",
    name: "Gunnar Henderson",
    mlbTeam: "BAL",
    positions: ["SS", "3B"],
    riskLevel: "low",
    depthStatus: "starter",
    estimatedValue: 45,
    isEligible: true,
  },
  {
    id: "4",
    name: "Francisco Lindor",
    mlbTeam: "NYM",
    positions: ["SS"],
    riskLevel: "low",
    depthStatus: "starter",
    estimatedValue: 40,
    isEligible: true,
  },
  {
    id: "5",
    name: "Elly De La Cruz",
    mlbTeam: "CIN",
    positions: ["SS", "3B"],
    riskLevel: "high",
    depthStatus: "starter",
    estimatedValue: 36,
    isEligible: true,
  },
  {
    id: "6",
    name: "Kyle Tucker",
    mlbTeam: "CHC",
    positions: ["OF"],
    riskLevel: "medium",
    depthStatus: "starter",
    estimatedValue: 39,
    isEligible: true,
  },
  {
    id: "7",
    name: "William Contreras",
    mlbTeam: "MIL",
    positions: ["C"],
    riskLevel: "low",
    depthStatus: "starter",
    estimatedValue: 28,
    isEligible: true,
  },
  {
    id: "8",
    name: "Adley Rutschman",
    mlbTeam: "BAL",
    positions: ["C"],
    riskLevel: "low",
    depthStatus: "starter",
    estimatedValue: 30,
    isEligible: true,
  },
  {
    id: "9",
    name: "Matt McLain",
    mlbTeam: "CIN",
    positions: ["SS", "2B"],
    riskLevel: "high",
    depthStatus: "starter",
    estimatedValue: 18,
    isEligible: true,
  },
  {
    id: "10",
    name: "Witt Jr.",
    mlbTeam: "KCR",
    positions: ["SS", "3B"],
    riskLevel: "low",
    depthStatus: "starter",
    estimatedValue: 48,
    isEligible: true,
  },
  {
    id: "11",
    name: "Yordan Alvarez",
    mlbTeam: "HOU",
    positions: ["OF"],
    riskLevel: "medium",
    depthStatus: "starter",
    estimatedValue: 42,
    isEligible: true,
  },
  {
    id: "12",
    name: "José Ramírez",
    mlbTeam: "CLE",
    positions: ["3B"],
    riskLevel: "low",
    depthStatus: "starter",
    estimatedValue: 44,
    isEligible: true,
  },
  {
    id: "13",
    name: "Shohei Ohtani",
    mlbTeam: "LAD",
    positions: ["OF"],
    riskLevel: "low",
    depthStatus: "starter",
    estimatedValue: 55,
    isEligible: true,
  },
  {
    id: "14",
    name: "Mookie Betts",
    mlbTeam: "LAD",
    positions: ["OF", "SS"],
    riskLevel: "medium",
    depthStatus: "starter",
    estimatedValue: 41,
    isEligible: true,
  },
  {
    id: "15",
    name: "Randy Arozarena",
    mlbTeam: "SEA",
    positions: ["OF"],
    riskLevel: "medium",
    depthStatus: "starter",
    estimatedValue: 25,
    isEligible: true,
  },
  {
    id: "16",
    name: "Zac Gallen",
    mlbTeam: "ARI",
    positions: ["SP"],
    riskLevel: "medium",
    depthStatus: "starter",
    estimatedValue: 22,
    isEligible: true,
  },
  {
    id: "17",
    name: "Gerrit Cole",
    mlbTeam: "NYY",
    positions: ["SP"],
    riskLevel: "high",
    depthStatus: "starter",
    estimatedValue: 20,
    isEligible: true,
  },
  {
    id: "18",
    name: "Spencer Strider",
    mlbTeam: "ATL",
    positions: ["SP"],
    riskLevel: "high",
    depthStatus: "starter",
    estimatedValue: 24,
    isEligible: true,
  },
  {
    id: "19",
    name: "Emmanuel Clase",
    mlbTeam: "CLE",
    positions: ["RP"],
    riskLevel: "low",
    depthStatus: "starter",
    estimatedValue: 16,
    isEligible: true,
  },
  {
    id: "20",
    name: "Pete Alonso",
    mlbTeam: "NYM",
    positions: ["1B"],
    riskLevel: "low",
    depthStatus: "starter",
    estimatedValue: 29,
    isEligible: true,
  },
];
